### ISSUE TITLE
we need an option to store outputs

### ISSUE THREAD

**Issue by dcb9** [ajvb/kala#164] opened 2017-10-14 01:55 UTC
add an option like this:

```json
POST /job/ 
{
  ... ... 
  "storeOutput": boolean
}
```

then have to think about how to store the outputs. the easiest way is store it with `JobStat` [See the code](https://github.com/ajvb/kala/pull/161/commits/f2a2d03e302aa202999e3f947b3574e6984e423f#diff-c14f612e9c955eee73aaed0dac80c487R76)

**Comment by gwoo** [comment] 2017-12-19 18:52
As of #177 the output is logged to stdout along with other kala log handling.

**Comment by gwoo** [comment] 2017-12-19 18:58
Also, this looks like a duplicate of #138. Closing this one in favor of the prior issue.

**Closed by gwoo** 2017-12-19 18:58 UTC
Labels: enhancement
